### ISSUE TITLE
PostCSS

### ISSUE THREAD

**Issue by balix** [balix/bijoostrap#12]
Créer nouvelle branche et test déploiement PostCSS sur Grunt (tester notamment MQPacker, CSSneat)

**Comment by balix** [comment]
Repartir de https://gist.github.com/ethyde/5eb4b553ca297f809c3e

**Comment by ethyde** [comment]
Branche crée, base de travail fonctionnel mise en place, reste à faire un peu de clean, mettre à jour les mixins.

(Ceci dit, en y repensant, et malgré les avantages des mixins, je me dit que cela peut-être confusant, tant sur le plan logique que syntaxique : avoir d'un côté une logique/syntaxe de variable "futurCSS" et de l'autre une logique/syntaxe de variable "Sass-like")

**Comment by balix** [comment]
Ok merci mec ;)

Pour les mixins, étant donné que la plupart sont là pour gérer les prefixs, on doit pouvoir s'en sortir juste avec des imports. Je pense qu'on peut les supprimer et on verra à l'usage s'il nous manque des choses.

**Comment by ethyde** [comment]
Et le nested ? :)

**Comment by ethyde** [comment]
Ça pour le compte c'est totalement agnostique et potentiellement pratique, je vais le laisser pour le moment, on verra à l'usage ?

**Comment by balix** [comment]
https://github.com/postcss/postcss-nested non ?
