### ISSUE TITLE
imagemin crash

### ISSUE THREAD

**Issue by Kodiakkb** [balix/bijoostrap#13]
Happened with several different files, png or jpg. Each time this routine crashes and is unable to even copy the images to dist. 

	Running "imagemin" task

	Running "imagemin:opti" (imagemin) task
	Verifying property imagemin.opti exists in config...OK
	Files: dev/images/breathing.jpg -> dist/images/breathing.jpg
	Files: dev/images/favicon.ico -> dist/images/favicon.ico
	Files: dev/images/footerLogo.png -> dist/images/footerLogo.png
	Files: dev/images/illustration.jpg -> dist/images/illustration.jpg
	Files: dev/images/logo.png -> dist/images/logo.png
	Files: dev/images/smallStage.jpg -> dist/images/smallStage.jpg
	Files: dev/images/stage01.jpg -> dist/images/stage01.jpg
	Files: dev/images/thumbnail.jpg -> dist/images/thumbnail.jpg
	Options: interlaced, optimizationLevel=3, progressive
	Warning: Error: spawn D:\projets\pro\Smll\site\smll\static\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin\vendor\jpegtran.exe ENOENT in file dev/images/smallStage.jpg Use --force to continue.

	Aborted due to warnings.

![smallstage](https://cloud.githubusercontent.com/assets/3121549/10508410/551dcc80-7327-11e5-8502-969a1ceff2d3.jpg)

**Comment by balix** [comment]
Avec quoi du créer tes images ?

**Comment by Kodiakkb** [comment]
Photoshop CS2, je t'ai jointe l'image sur laquelle il plante.

**Comment by ethyde** [comment]
J'ai l'impression que cela ressemble à ça : https://github.com/gruntjs/grunt-contrib-imagemin/issues/96 , non ?

**Comment by ethyde** [comment]
Tu peux essayer de clear le cache de NPM : https://github.com/npm/npm/wiki/Troubleshooting#try-clearing-the-npm-cache

**Comment by Kodiakkb** [comment]
@ethyde le cache clean ne change rien

**Comment by balix** [comment]
Il n'y a que cette image spécifique qui bloque ?

**Comment by Kodiakkb** [comment]
Non, n'importe laquelle, png ou jpeg. Si j'enlève celle-là il chouine sur une autre.

**Comment by Kodiakkb** [comment]
Il est très content avec le favicon.ico mais il plante même avec le apple-touch-icon.png qui est dans le repo.

**Comment by balix** [comment]
Quelle est ta version de Node et de NPM ?

**Comment by Kodiakkb** [comment]
I removed "read only" on AppData\Roaming\npm (but I don't know if it has anything to do with my issue).

I manually removed grunt-contrib-imagemin, then called npm install and everything works fine.

**Comment by ethyde** [comment]
Good news !

I don't know about readonly, but yes, sometime remove and download fresh install was the solution !
